# 钉钉 rss 推送机器人
name: DingDingRssBot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0/1 * * *'
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.7.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.6
    - name: Install dependencies
      run: |
        ls
        pip install -r ./robot/requirements.txt
    - name: send rss
      run: |
        python ./robot/rss.py
